[phases.setup]
nixPkgs = ["nodejs-22_x", "openssl"]

[phases.install]
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node dist/src/main.js"
